apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sk010-test-app
  namespace: skala-argocd     
spec:
  project: default              

  source:
    repoURL: 'https://github.com/seo-youngjae/test-app.git'
    targetRevision: gitops    
    path: k8s                 

  destination:
    server: 'https://96BD83E8CE5CE0396D006BC5CEB350B0.gr7.ap-northeast-2.eks.amazonaws.com'
    namespace: skala-practice 

  syncPolicy:
    automated:
      prune: true             
      selfHeal: true          
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=background
