apiVersion: v1
kind: Service
metadata:
  name: sk010-test-app
  namespace: skala-practice
spec:
  selector:
    app: sk010-test-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
